name: Trigger Pricing List Workflow

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true

jobs:
  trigger-pricing-list:
    runs-on: ubuntu-latest
    steps:
      # Step 1: A curl request to trigger the workflow_dispatch in the target repo
      - name: Trigger Pricing List workflow via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} 
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}" \
            https://api.github.com/repos/layer5labs/meshery-extensions-packages/actions/workflows/generate-pricing-list.yml/dispatches \
            -d '{"ref":"master", "inputs":{"spreadsheet_uri":"${{ inputs.spreadsheet_uri }}"}}'
