name: Trigger Pricing List Workflow

on:
  workflow_dispatch:

jobs:
  trigger-pricing-list:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pricing List workflow via GitHub API
        run: |
          # Default spreadsheet link
          SPREADSHEET_URI="http://docs.google.com/spreadsheets/d/1Ck_5q7U_vLSIDTtplugG3pCVC5zugXgTHtO7T7-yL8g/export?format=csv&gid=829069645&single=true&output=csv"

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}" \
            https://api.github.com/repos/layer5labs/meshery-extensions-packages/actions/workflows/generate-pricing-list.yml/dispatches \
            -d "{\"ref\":\"master\", \"inputs\":{\"spreadsheet_uri\":\"${SPREADSHEET_URI}\"}}"
